- hosts: ci
  gather_facts: no
  become: yes

  vars:
    image_name: '{{ grafana_registry_dir }}'
    image_tag: '{{ grafana_tag }}'
    registry_dir: '{{ grafana_registry_dir }}'

  vars_files:
    - group_vars/grafana.yml

  roles:
    - ping
    - docker-image-build
