- hosts: localhost
  gather_facts: no
  become: no

  tasks:
    - name: remove some hosts from known_hosts
      shell: 'ssh-keygen -R {{ item }}'
      with_items: '{{ groups.all }}'

    - name: add some hosts to known_hosts
      shell: 'ssh-keyscan -H {{ item }} | grep ssh-rsa >> ~/.ssh/known_hosts'
      with_items: '{{ groups.all }}'

- hosts: develop
  gather_facts: no
  become: yes

  tasks:
    - ping:

    - name: configure docker daemon to use insecure registry
      lineinfile:
        dest: /etc/docker/daemon.json
        create: yes
        line: ' { "insecure-registries": ["{{ registry_host }}:{{ registry_port }}"] }'
        owner: root
        group: root
        mode: 0600

    - name: restart docker daemon
      service:
        name: docker
        state: restarted
