- hosts: tornado
  gather_facts: no
  become: yes

  tasks:
    - ping:

    - name: present tornado docker container
      docker_container:
        name: 'tornado_{{ tornado_tag }}_{{ inventory_hostname }}_{{ item }}'
        image: '{{ tornado_image }}:{{ tornado_tag }}'
        state: present
        volumes: '{{ tornado_volumes }}'
        ports:
          - '{{ item }}:{{ tornado_port }}'
        restart_policy: on-failure
        restart_retries: 5
        env: '{{ tornado_env }}'
      with_items: '{{ tornado_upstream_ports[:tornado_cph] }}'
