- hosts: mongo
  gather_facts: no
  become: yes

  tasks:
    - ping:

    - name: present mongo docker container
      docker_container:
        name: 'mongo_{{ mongo_tag }}_{{ inventory_hostname }}'
        image: '{{ mongo_image }}:{{ mongo_tag }}'
        state: present
        volumes: '{{ mongo_volumes }}'
        ports: '{{ mongo_ports }}'
    #    links:
        restart_policy: on-failure
        restart_retries: 5
        env: '{{ mongo_env }}'
