registry_tag: 2
registry_host: '{{ groups["registry"][0] }}'
registry_port: 5000
registry_cph: 1

nodeexporter_tag: v1
nodeexporter_tag_prev: v0
nodeexporter_registry_dir: nodeexporter
nodeexporter_port: 9100
nodeexporter_cph: 1

cadvisor_tag: v1
cadvisor_tag_prev: v0
cadvisor_registry_dir: cadvisor
cadvisor_port: 8080
cadvisor_cph: 1

prometheus_tag: v1
prometheus_tag_prev: v0
prometheus_registry_dir: prometheus
prometheus_host: '{{ groups["prometheus"][0] }}'
prometheus_port: 9090
prometheus_cph: 1

grafana_tag: v1
grafana_tag_prev: v0
grafana_registry_dir: grafana
grafana_host: '{{ groups["grafana"][0] }}'
grafana_port: 3000
grafana_cph: 1

nginx_front_tag: v1
nginx_front_tag_prev: v0
nginx_front_registry_dir: nginx_front
nginx_front_host: '{{ groups["nginx_front"][0] }}'
nginx_front_port: 80
nginx_front_cph: 1

tornado_tag: v1
tornado_tag_prev: v0
tornado_registry_dir: tornado
tornado_host: '{{ groups["tornado"][0] }}'
tornado_port: 8888
tornado_upstream_ports:
  - 9600
  - 9601
  - 9602
  - 9603
  - 9604
  - 9605
  - 9606
  - 9607
  - 9608
  - 9609
tornado_cph: 5

redis_tag: v1
redis_tag_prev: v0
redis_registry_dir: redis
redis_host: '{{ groups["redis"][0] }}'
redis_port: 6379
redis_cph: 1

mongo_tag: v1
mongo_tag_prev: v0
mongo_registry_dir: mongo
mongo_host: '{{ groups["mongo"][0] }}'
mongo_port: 27017
mongo_cph: 1
